#!/usr/bin/env python3
#
# Generate C source files for wavetables
#

import math

nyquist = 24000

def saw(fraction, harmonics):
    sum = 0
    for i in range(1, harmonics+1):
        sum += (1/i) * math.sin(i * fraction * 2*math.pi)
    return sum

def note2hz(note):
    # Get frequency of MIDI note number (note 69 is middle A @ 440 Hz)
    return 2**((note - 69) / 12) * 440

def make_tables(function, firstNote, notesPerTable, tableCount, tableLength):
    output = "{\n"
    for tableNum in range(tableCount):
        highestFreq = note2hz(firstNote + (tableNum + 1) * notesPerTable)
        harmonics = (int)(nyquist/highestFreq)
        data = list(map(lambda s: function(s/tableLength, harmonics), range(tableLength)))
        output += "    { // notes %d - %d, up to %.2f Hz (%d harmonics)" % (firstNote + tableNum * notesPerTable,
                                                                            firstNote + (tableNum+1) * notesPerTable - 1,
                                                                            highestFreq, harmonics)
        for i in range(len(data)):
            if not i % 8:
                output += "\n        "
            output += "%.06f, " % data[i]
            
        output += "\n    },\n"

    output += "}"
    return output

if __name__ == "__main__":
    tableCount = 10
    tableLength = 32

    t = make_tables(saw, 8, 12, tableCount, tableLength)
    print("""/*
 * Saw wavetable generated by make_wavetable.py
 */
""")
    print("#define WT_TABLES %d" % tableCount)
    print("#define WT_LENGTH %d" % tableLength)
    print("#define WT_FIRST_NOTE 8")
    print("#define WT_NOTES_PER_TABLE 8")
    print("static const float wtSaw[WT_TABLES][WT_LENGTH] = %s;\n" % t)

