name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install shit
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libjack-dev
    - name: make
      run: make -C fw
